module(
    name = "rules_jsonnet",
    version = "0.7.2",
)

bazel_dep(name = "bazel_skylib", version = "1.8.1")
bazel_dep(name = "jsonnet", version = "0.21.0")
bazel_dep(name = "jsonnet_go", version = "0.21.0")
bazel_dep(name = "rules_python", version = "1.7.0")
bazel_dep(name = "rules_rust", version = "0.68.1")

jsonnet = use_extension("//jsonnet:extensions.bzl", "jsonnet")
use_repo(jsonnet, "rules_jsonnet_toolchain")

register_toolchains("@rules_jsonnet_toolchain//:toolchain")

rust_host = use_extension("@rules_rust//rust:extensions.bzl", "rust_host_tools")
rust_host.host_tools(
    name = "rust_host_tools_jsonnet",
    sha256s = {
        "2025-07-01/rustc-nightly-aarch64-apple-darwin.tar.xz": "b5fb4b5272fea4d4ef6e3896e484e9748fda4f29be428ae3a55c22f70566b54c",
        "2025-07-01/clippy-nightly-aarch64-apple-darwin.tar.xz": "a0715713220f6cb56031a86c91de7a26d1f89d149afc2e01af625a89ca63f673",
        "2025-07-01/cargo-nightly-aarch64-apple-darwin.tar.xz": "4eb240f69df9f9159c6fef128c3b7c24e5e1ae8aaf1357de4924fd518bd54941",
        "2025-07-01/llvm-tools-nightly-aarch64-apple-darwin.tar.xz": "ab8d9977ba3187819008b70dab317654bb290fc220cfea35b4f2ea165ce32e70",
        "2025-07-01/rust-std-nightly-aarch64-apple-darwin.tar.xz": "da6c8e6f256bb6512485db068d35109a3c77ccac678bc28134665cd1b547863b",
        "2025-07-01/rustc-nightly-x86_64-unknown-linux-gnu.tar.xz": "314716de24ef1ac3cb0e2486f07f836405278b9be322e2061d2b7256d38752bf",
        "2025-07-01/clippy-nightly-x86_64-unknown-linux-gnu.tar.xz": "31045a959324afec81883d041a1e5fdf4016df37ed0e7302edd18bb38ff3ccd2",
        "2025-07-01/cargo-nightly-x86_64-unknown-linux-gnu.tar.xz": "450c5e0e91edb56d20122949e45d8bf25d42ce86f7ba26ec072f93617cf57bd4",
        "2025-07-01/llvm-tools-nightly-x86_64-unknown-linux-gnu.tar.xz": "bce9c76a9d8f32b04e370e14b358895897b175a366d649b9535eb1f7c91a8aa3",
        "2025-07-01/rust-std-nightly-x86_64-unknown-linux-gnu.tar.xz": "f5b0c21177fe6259e19d7a39c9a0f877f595e34468a0838a20b3c401f2b679fa",
        "2025-07-01/rustc-nightly-aarch64-unknown-linux-gnu.tar.xz": "6f1b5f577a056d620b9745abd3e8f26f04cb3a38631aeea2eba9e08accc795d8",
        "2025-07-01/clippy-nightly-aarch64-unknown-linux-gnu.tar.xz": "7594dba8152270c8fedbf60500c3ddb5dbc53922fd66b1cae4f7ecd3523e167a",
        "2025-07-01/cargo-nightly-aarch64-unknown-linux-gnu.tar.xz": "efebb3bfbdbe6a265e71731fffbf9e60539128aaa7bbd8a523f66e1915f64230",
        "2025-07-01/llvm-tools-nightly-aarch64-unknown-linux-gnu.tar.xz": "5682ad4f8b89ffbd365fc4ea6c420300d614d9b7281405b800e80ff3e2d24671",
        "2025-07-01/rust-std-nightly-aarch64-unknown-linux-gnu.tar.xz": "cb9fc0f20cbd484e1f20dee3498a1a785fafd662ea39b3fb064773f9427262a6",
    },
    version = "nightly/2025-07-01",
)
use_repo(rust_host, "rust_host_tools_jsonnet")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = ["1.88.0"],
)
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")

crate = use_extension("@rules_rust//crate_universe:extension.bzl", "crate")
crate.spec(
    # Binary artifacts can't be depended upon without specifically marking the
    # artifact as `bin`.
    artifact = "bin",
    package = "jrsonnet",
    version = "0.5.0-pre95",
)

# Required for rules_rust to generate binary targets for the Jrsonnet crate.
crate.annotation(
    crate = "jrsonnet",
    gen_binaries = ["jrsonnet"],
)
crate.from_specs(
    name = "crates_jsonnet",
    host_tools = "@rust_host_tools_jsonnet",
)
use_repo(crate, "crates_jsonnet")
