module(
    name = "rules_jsonnet",
    version = "0.7.2",
)

bazel_dep(name = "bazel_skylib", version = "1.8.1")
bazel_dep(name = "jsonnet", version = "0.22.0")
bazel_dep(name = "jsonnet_go", version = "0.22.0")
bazel_dep(name = "rules_python", version = "1.7.0")
bazel_dep(name = "rules_rs", version = "0.0.95")

jsonnet = use_extension("//jsonnet:extensions.bzl", "jsonnet")
use_repo(jsonnet, "rules_jsonnet_toolchain")

register_toolchains("@rules_jsonnet_toolchain//:toolchain")

rules_rust = use_extension("@rules_rs//rs:rules_rust.bzl", "rules_rust")
use_repo(rules_rust, "rules_rust")

rust_toolchains = use_extension("@rules_rs//rs/toolchains:module_extension.bzl", "toolchains")
use_repo(rust_toolchains, "default_rust_toolchains")

register_toolchains("@default_rust_toolchains//:all")

crate = use_extension("@rules_rs//rs:extensions.bzl", "crate")
crate.from_cargo(
    name = "crates_jsonnet",
    cargo_lock = "//:Cargo.lock",
    cargo_toml = "//:Cargo.toml",
    platform_triples = [
        "aarch64-apple-darwin",
        "aarch64-unknown-linux-gnu",
        "x86_64-apple-darwin",
        "x86_64-unknown-linux-gnu",
    ],
)
crate.annotation(
    crate = "jrsonnet",
    gen_binaries = ["jrsonnet"],
)
use_repo(crate, "crates_jsonnet")
